MySQL:
  use-MySQL: false
  host: "localhost"
  port: "3306"
  database: ""
  username: "root"
  password: ""
  SSL: false

# You can currently only have one party manager.
# A party manager decided viable targets for skills with AoE effects
# Or more advanced projectile based skills.
# Currently supported: Factions3, FactionsUUID, Parties, Towny and mcMMO

party-managers:
  - "mcMMO"
#  - "Towny"

# You can have as many protection managers as you like
# As long as they are supported by the plugin.
# It is however recommended to not go above 2-3.
# If you wish to not use any, simple remove all from the list below.
# Currently supported: Factions3, FactionsUUID, WorldGuard 7.0+ and Towny
protection-managers:
  - "Factions"
#  - "WorldGuard"
#  - "Towny"

use-pvp-toggle: false

mana:
  enabled: true
  recovery-delay: 2
  recovery-amount: 2

leveling:
  max-level: 30
  upgrade-point-interval: 1
  unlock-point-interval: 5

items:
  spellbook:
    lore:
      - "Hold this item and right click"
      - "to enter spellmode."
      - "Can also be used to exit spellmode."

class-change:
  #Set to -1 to disable swap cost
  costs-after-level: 9
  material: GOLD_INGOT
  amount: 32

exp:
  global-multiplier: 1.0
  source-blacklist:
    mcmmo-skills:
      - Acrobatics

garbage-collection:
  # Time that should pass between garbage collection.
  # Set to 0 to disable garbage collection.
  timer: 120
  # Will send message in console if true.
  verbose: false