name: ClassesOfDragonfall
version: ${project.version}
main: me.xepos.rpg.XRPG
api-version: 1.16
softdepend:
  - Factions
  - Parties
  - WorldGuard
  - mcMMO
  - LevelledMobs
  - Essentials
commands:
  xrpgdebug:
    description: debug command
    usage: /<command> <number>
  xrpgreload:
    description: reloads xrpg configuration
    usage: /<command>
  spellmode:
    description: switch to or from spell casting mode
    usage: /<command> <on|off|toggle|status>
    aliases:
      - sm
  spellbook:
    description: open your spellbook
    usage: /<command>
    aliases:
      - sb
  tree:
    description: opens the skilltree for your class
    usage: /<command>
    aliases:
      - skills
      - talents
  xrpginfo:
    description: get information about a player or skill
    usage: /<command> (player|skill) <player|skillId>
  class:
    description: change or toggle your class
    usage: /<command> <select|change|enable|disable|toggle>
    permission: class.change
  xrpgadmin:
    description: a set of administration commands
    usage: /<command> ...
    permission: xrpg.admin

permissions:
  xrpg.*:
    description: allows all commands for this plugin
    default: op
    children:
      xrpg.admin: true
      xrpg.debug: true
  xrpg.admin:
    description: allows administration commands for this plugin
    default: op
    children:
      xrpg.admin.add.level: true
      xrpg.admin.add.skill: true
      xrpg.admin.create.eventspell: true
      xrpg.admin.reset.skilltree: true
  xrpg.admin.add.level:
    description: allows to add levels or experience to players
    default: op
  xrpg.admin.add.skill:
    description: allows to add skills to players
    default: op
  xrpg.admin.create.eventspell:
    description: allows to create event spell items
    default: op
  xrpg.admin.reset.skilltree:
    description: allows to reset other player's skilltree
    default: op
  xrpg.tree.*:
    description: allows all interactions for the player's own skilltree
    default: true
    children:
      xrpg.tree.open: true
      xrpg.tree.reset: true
  xrpg.tree.open:
    description: allows the player to open the tree menu
    default: true
  xrpg.tree.reset:
    description: allows the player to reset their skilltree
    default: op
  xrpg.spellbook.*:
    description: allows players all spellbook interactions
    default: true
  xrpg.class.*:
    description: allows all class commands
    default: op
    children:
      xrpg.class.change: true
  xrpg.class.change:
    description: allows the player to change or select their class
    default: op
  xrpg.debug.*:
    description: debug commands for administrators
    default: op