name: ClassesOfDragonfall
version: ${project.version}
main: me.xepos.rpg.XRPG
api-version: 1.16
softdepend:
  - Factions
  - Parties
  - WorldGuard
  - mcMMO
commands:
  xrpgdebug:
    description: debug command
    usage: /<command> <number>
  xrpgreload:
    description: reloads xrpg configuration
    usage: /<command>
  spellmode:
    description: switch to or from spell casting mode
    usage: /<command> <on|off|toggle|status>
    aliases:
      - sm
  spellbook:
    description: open your spellbook
    usage: /<command>
    aliases:
      - sb
  tree:
    description: open tree
    usage: /<command>
  xrpginfo:
    description: get information about a player or skill
    usage: /<command> (player|skill) <player|skillId>