name: ClassesOfDragonfall
version: ${project.version}
main: me.xepos.rpg.XRPG
api-version: 1.16
softdepend:
  - Factions
  - Parties
  - WorldGuard
  - mcMMO
  - LevelledMobs
commands:
  xrpgdebug:
    description: debug command
    usage: /<command> <number>
  xrpgreload:
    description: reloads xrpg configuration
    usage: /<command>
  spellmode:
    description: switch to or from spell casting mode
    usage: /<command> <on|off|toggle|status>
    aliases:
      - sm
  spellbook:
    description: open your spellbook
    usage: /<command>
    aliases:
      - sb
  tree:
    description: opens the skilltree for your class
    usage: /<command>
    aliases:
      - skills
      - talents
  xrpginfo:
    description: get information about a player or skill
    usage: /<command> (player|skill) <player|skillId>
  class:
    description: change or toggle your class
    usage: /<command> <select|change|enable|disable|toggle>
  xrpgadmin:
    description: a set of administration commands
    usage: /<command> ...

permissions:
  xrpg.*:
    description: allows all commands for this plugin
    default: op
    children:
      xrpg.admin: true
  xrpg.admin:
    description: allows administration commands for this plugin
    default: op